const card = (n, prefix = "要点") => Array.from({ length: n }, (_, i) => ({ title: `${prefix}${i + 1}`, desc: "現場の作業を減らし、判断を早める" }));
const base = (title) => ({ title, takeaway: "結論を一文で示し、判断を早める" });

export const allLayoutSlides = [
  { type: "title", title: "全レイアウト検証デッキ", subtitle: "HTMLエンジンの描画確認", date: "2026年9月" },
  { type: "section", title: "第1章 現状", takeaway: "まず現状を共有する" },
  { type: "hero", title: "現場の時間を、お客様へ", takeaway: "削減した時間を接客に回す", visualAsset: "storeOperations", photoMotion: "zoom" },
  { type: "statement", title: "ひと言で", text: "作業を減らすのではなく、**判断を早める**", takeaway: "それが今回の改革の本質です" },
  { type: "content", ...base("本文"), points: ["背景：人手不足が続く", "課題：作業が属人化している", "方針：仕組みで標準化する"] },
  { type: "content", ...base("本文2列"), twoColumn: true, points: ["項目A", "項目B", "項目C", "項目D"] },
  { type: "agenda", ...base("アジェンダ"), items: ["背景：なぜ今か", "現状：何が起きているか", "提案：何をするか"] },
  { type: "compare", ...base("対比"), leftTitle: "現状", rightTitle: "目指す姿", leftItems: ["紙で管理"], rightItems: ["端末で管理"] },
  { type: "beforeAfter", ...base("前後"), leftTitle: "Before", rightTitle: "After", leftItems: ["手作業"], rightItems: ["自動化"] },
  { type: "process", ...base("プロセス"), steps: ["準備：目的を共有", "実行：手順を実施", "確認：結果を振り返る"] },
  { type: "processList", ...base("工程リスト"), steps: ["準備", "実行", "確認", "改善", "定着", "展開"] },
  { type: "flowChart", ...base("フロー"), flows: [{ steps: ["受付", "確認", "承認"] }, { steps: ["発注", "納品"] }] },
  { type: "timeline", ...base("タイムライン"), milestones: [{ label: "開始", date: "4月", state: "done" }, { label: "展開", date: "7月", state: "next" }, { label: "定着", date: "10月" }] },
  { type: "diagram", ...base("レーン図"), lanes: [{ title: "店舗", items: ["発注", "検品"] }, { title: "本部", items: ["分析"] }] },
  { type: "cycle", ...base("サイクル"), centerText: "品質向上", items: [{ label: "計画" }, { label: "実行" }, { label: "評価" }, { label: "改善" }] },
  { type: "cards", ...base("カード"), items: card(3) },
  { type: "headerCards", ...base("見出しカード"), items: card(4) },
  { type: "bulletCards", ...base("要点カード"), items: card(3) },
  { type: "table", ...base("表"), headers: ["項目", "現状", "目標"], rows: [["作業時間", "120h", "80h"], ["廃棄率", "3.0%", "2.5%"]] },
  { type: "quote", ...base("引用"), text: "現場の声を仕組みに変える", author: "店舗オーナー" },
  { type: "kpi", ...base("KPI"), items: [{ label: "削減時間", value: "120h", change: "月間", status: "good" }, { label: "短縮率", value: "42%", status: "good" }] },
  { type: "faq", ...base("FAQ"), items: [{ q: "費用は？", a: "既存端末を活用する" }, { q: "期間は？", a: "3か月で定着する" }] },
  { type: "statsCompare", ...base("数値比較"), leftTitle: "前", rightTitle: "後", stats: [{ label: "時間", leftValue: "95分", rightValue: "54分", trend: "down" }] },
  { type: "triangle", ...base("トライアングル"), items: card(3) },
  { type: "pyramid", ...base("ピラミッド"), levels: [{ title: "理念", description: "目指す姿" }, { title: "戦略", description: "重点施策" }, { title: "実行", description: "日々の行動" }] },
  { type: "stepUp", ...base("ステップアップ"), items: card(3) },
  { type: "imageText", ...base("グラフ"), image: { chartType: "bar", data: { title: "部署別", items: [{ label: "営業", value: 78 }, { label: "企画", value: 66 }] } }, points: ["営業が最も高い"] },
  { type: "imageText", ...base("複数系列"), image: { chartType: "multi-line", data: { xAxisLabels: ["4月", "5月"], series: [{ label: "A", values: [1, 2] }, { label: "B", values: [2, 3] }] } }, points: ["両方とも増加"] },
  { type: "imageText", ...base("積み上げ"), image: { chartType: "stacked-bar", data: { legendLabels: ["A", "B"], barData: [{ label: "4月", values: [1, 2] }, { label: "5月", values: [2, 2] }] } }, points: ["構成比が変化"] },
  { type: "imageText", ...base("ドーナツ"), image: { chartType: "donut", data: { items: [{ label: "A", value: 60 }, { label: "B", value: 40 }] } }, points: ["Aが過半"] },
  { type: "grid2x2", ...base("2×2"), items: card(4) },
  { type: "headerTwoColumn", ...base("2列"), items: card(2) },
  { type: "headerThreeSummary", ...base("3列まとめ"), items: card(3), summary: "3要素をセットで提供する" },
  { type: "funnel", ...base("ファネル"), levels: [{ title: "認知" }, { title: "来店" }, { title: "購入" }] },
  { type: "venn", ...base("ベン図"), items: card(3) },
  { type: "gantt", ...base("ガント"), periods: ["4月", "5月", "6月", "7月"], items: [{ title: "設計", desc: "要件", start: 0, span: 1 }, { title: "開発", start: 1, span: 2 }] },
  { type: "orgChart", ...base("組織図"), root: "責任者", items: card(3) },
  { type: "checklist", ...base("チェック"), items: [{ title: "承認", desc: "確認済み", done: true }, { title: "検査", desc: "未完了" }] },
  { type: "matrix", ...base("マトリクス"), xLabel: "難易度", yLabel: "重要度", items: card(4) },
  { type: "roadmap", ...base("ロードマップ"), items: card(3, "Phase") },
  { type: "dashboard", ...base("ダッシュボード"), items: [{ label: "売上", value: "102%" }, { label: "客数", value: "98%" }], image: { chartType: "line", data: { items: [{ label: "4月", value: 100 }, { label: "5月", value: 102 }] } } },
  { type: "swot", ...base("SWOT"), items: card(4) },
  { type: "waterfall", ...base("内訳"), unit: "時間", items: [{ label: "資料作成", value: 150 }, { label: "議事録", value: 90 }, { label: "手戻り", value: -20 }, { label: "合計", value: 220, total: true }] },
  { type: "logicTree", ...base("要因分解"), root: "活用率の部門差", branches: [{ title: "業務との接点", items: ["棚卸しが未実施"], highlight: true }, { title: "相談先がない", items: ["推進役が不在", "離脱する"] }] },
  { type: "executiveSummary", ...base("サマリー"), conclusion: "全店展開を提案する", items: card(3), action: "予算承認を依頼する" },
  { type: "imageText", ...base("切り口で並び替え"), source: "社内集計 2026年", image: { chartType: "rank", data: { title: "部門別の削減時間", unit: "時間", highlight: "営業", views: [{ label: "月合計", items: [{ label: "営業", value: 320 }, { label: "企画", value: 410 }, { label: "総務", value: 150 }] }, { label: "1人あたり", items: [{ label: "営業", value: 8 }, { label: "企画", value: 6 }, { label: "総務", value: 5 }] }] } }, points: ["1人あたりでは営業が最大"] },
  { type: "imageText", ...base("前後の差"), image: { chartType: "shift", data: { title: "1件あたりの時間", unit: "分", beforeLabel: "前", afterLabel: "後", items: [{ label: "下書き", before: 90, value: 35 }, { label: "確認", before: 30, value: 28 }] } }, points: ["下書きが大きく減った"] },
  { type: "simulator", ...base("試算"), inputs: [{ label: "人数", value: 120, min: 50, max: 600, step: 10, unit: "人" }, { label: "1人あたり", value: 12, min: 2, max: 30, unit: "時間" }], formula: "a × b", resultLabel: "月の削減時間", resultUnit: "時間", compareLabel: "目標", compareValue: 3000 },
  { type: "gap", ...base("不足と打ち手"), unit: "時間", targetLabel: "目標", target: 3000, currentLabel: "現状", current: 1440, measures: [{ title: "テンプレート", value: 620, desc: "指示文30種" }, { title: "推進役", value: 540 }, { title: "入力ルール", value: 480 }] },
  { type: "closing", title: "次のアクション", message: "10月までに全店展開の計画を確定する" },
];

// Body slides take turns between looks (rows, cards, a statement, left and right), as a well-made deck does.
const BODY = [
  (title) => ({ type: "content", title, takeaway: "短い結論", points: ["要点A", "要点B"] }),
  (title) => ({ type: "cards", title, takeaway: "短い結論", items: [{ title: "要点A", desc: "説明A" }, { title: "要点B", desc: "説明B" }] }),
  (title) => ({ type: "statement", title, text: "判断を**早める**" }),
  (title) => ({ type: "compare", title, takeaway: "短い結論", leftTitle: "現状", rightTitle: "目指す姿", leftItems: ["手作業"], rightItems: ["自動化"] }),
];

export const shortDeck = (count = 5) => ({
  deckTitle: "テスト資料",
  purpose: "検証",
  audience: "役員",
  slideData: [
    { type: "title", title: "テスト資料" },
    ...Array.from({ length: count - 2 }, (_, i) => BODY[i % BODY.length](`本文${i + 1}`)),
    { type: "closing", title: "次のアクション", message: "来週までに決める" },
  ],
});
